const menuData = [{
    name: '首页',
    href: '/'
}, {
    name: '实践',
    href: '/practice',
    children: [{
        name: '实践案例',
        href: '/practice/cases'
    }, {
        name: '框架使用',
        href: '/practice/overall'
    }, {
        name: '成员',
        href: '/practice/members'
    }, {
        name: '覆盖',
        href: '/practice/list'
    }]
}, {
    name: '组件',
    href: '/react',
    children: [{
        name: 'React Salt',
        href: '/react/salt'
    }, {
        name: '快速上手',
        href: '/react/get-started'
    }, {
        name: '基础',
        className: 'side-subtitle'
    }, {
        name: 'Button',
        href: '/react/components/button',
        className: 'side-subchildren'
    }, {
        name: 'Layout',
        href: '/react/components/csslayout',
        className: 'side-subchildren'
    }, {
        name: '表单',
        className: 'side-subtitle'
    }, {
        name: 'Form',
        href: '/react/components/form',
        className: 'side-subchildren'
    }, {
        name: 'DatePicker',
        href: '/react/components/datepicker',
        className: 'side-subchildren'
    }, {
        name: 'Input',
        href: '/react/components/input',
        className: 'side-subchildren'
    }, {
        name: 'Select',
        href: '/react/components/select',
        className: 'side-subchildren'
    }, {
        name: '展示',
        className: 'side-subtitle'
    }, {
        name: 'Grid',
        href: '/react/components/grid',
        className: 'side-subchildren'
    }, {
		name: 'Panel',
		href: '/react/components/panel',
        className: 'side-subchildren'
    }, {
        name: 'DropDown',
        href: '/react/components/dropdown',
        className: 'side-subchildren'
    }, {
        name: 'Pop',
        href: '/react/components/pop',
        className: 'side-subchildren'
    }, {
        name: 'Collapse',
        href: '/react/components/collapse',
        className: 'side-subchildren'
    }, {
        name: 'Alert',
        href: '/react/components/alert',
        className: 'side-subchildren'
    }, {
        name: 'Dialog',
        href: '/react/components/dialog',
        className: 'side-subchildren'
    }, {
        name: 'SweetAlert',
        href: '/react/components/sweetalert',
        className: 'side-subchildren'
    }, {
        name: 'Timeline',
        href: '/react/components/timeline',
        className: 'side-subchildren'
    }, {
        name: 'Loading',
        href: '/react/components/loading',
        className: 'side-subchildren'
    }, {
        name: '导航',
        className: 'side-subtitle'
    }, {
        name: 'BreadCrumb',
        href: '/react/components/breadcrumb',
        className: 'side-subchildren'
    }, {
        name: 'Pagination',
        href: '/react/components/pagination',
        className: 'side-subchildren'
    }, {
		name: 'Tree',
		href: '/react/components/tree',
        className: 'side-subchildren'
    }, {
        name: 'Tab',
        href: '/react/components/tab',
        className: 'side-subchildren'
	}, {
        name: '更新日志',
        href: '/react/logs'
    }]
},{
    name: '资源',
    href: '/resource',
	children: [{
		name: '聊天室',
		href: 'https://gitter.im/Sobranier/react-salt?utm_source=share-link&utm_medium=link&utm_campaign=share-link'
	}, {
        name: 'GitHub',
        href: 'https://github.com/react-salt'
    }]
}];

const member = [{
    link: 'https://github.com/Sobranier',
    img: 'https://avatars3.githubusercontent.com/u/7440073?v=3&s=230'
}, {
    img: 'https://avatars3.githubusercontent.com/u/1124573?v=3&s=230'
}, {
    img: 'https://avatars1.githubusercontent.com/u/3753637?v=3&s=230'
}, {
    img: 'https://avatars3.githubusercontent.com/u/7994652?v=3&s=230'
}, {
    img: 'https://avatars3.githubusercontent.com/u/8955196?v=3&s=230'
}];

export default {
    menuData: menuData,
    member: member
}
